from pydantic import BaseModel, Field, field_validator
from pydantic_core import core_schema
from enum import Enum
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any, Annotated
from bson import ObjectId

# Utility function to get current UTC time
def get_utc_now():
    return datetime.now(timezone.utc)

class PyObjectId(ObjectId):
    """Custom Pydantic type for MongoDB ObjectId."""
    
    @classmethod
    def __get_pydantic_core_schema__(cls, source_type, handler):
        return core_schema.no_info_plain_validator_function(
            cls.validate,
            serialization=core_schema.plain_serializer_function_ser_schema(
                lambda x: str(x)
            )
        )

    @classmethod
    def validate(cls, v):
        if isinstance(v, ObjectId):
            return v
        if isinstance(v, str):
            if not ObjectId.is_valid(v):
                raise ValueError("Invalid ObjectId")
            return ObjectId(v)
        raise ValueError("Invalid ObjectId")


class Role(str, Enum):
    """User roles in the chat system."""
    USER = "user"
    BOT = "bot"

class ToolType(str, Enum):
    """Types of tools that can be used in chat."""
    KNOWLEDGE_BASE = "knowledge_base"
    WCA_DATA = "wca_data"
    WCA_LIVE = "wca_live"
    SOLVE_ANALYSIS = "solve_analysis"

class FeedbackType(str, Enum):
    """User feedback types for bot messages."""
    LIKE = "like"
    DISLIKE = "dislike"

class MessageFeedback(BaseModel):
    """User feedback on a bot message."""
    feedback_type: FeedbackType
    comment: Optional[str] = Field(None, max_length=500)
    created_at: datetime = Field(default_factory=get_utc_now)

class ToolUsage(BaseModel):
    """Information about a tool used during message generation."""
    tool_type: ToolType
    query: str
    result_summary: Optional[str] = None
    execution_time_ms: Optional[float] = None
    metadata: Optional[Dict[str, Any]] = None

class MessageMetadata(BaseModel):
    """Metadata for bot messages in agentic RAG system."""
    tools_used: List[ToolUsage] = Field(default_factory=list)
    sources: List[Dict[str, Any]] = Field(default_factory=list)  # RAG sources/citations
    confidence_score: Optional[float] = None
    total_processing_time_ms: Optional[float] = None
    model_version: Optional[str] = None
    token_count: Optional[int] = None

class Message(BaseModel):
    """
    Represents a message in a chat session.

    Attributes:
        id (str): Unique identifier for the message.
        chat_session_id (str): Identifier for the chat session the message belongs to.
        user_id (str): Identifier for the user who sent the message.
        role (Role): Role of the user who sent the message (user or bot).
        content (str): Content of the message.
        metadata (MessageMetadata): Metadata associated with the message.
        feedback (MessageFeedback): User feedback on the message.
        created_at (datetime): Timestamp when the message was created.
    """
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    chat_session_id: PyObjectId = Field(..., index=True)
    user_id: str = Field(..., index=True)
    role: Role
    content: str
    metadata: Optional[MessageMetadata] = None
    feedback: Optional[MessageFeedback] = None
    created_at: datetime = Field(default_factory=get_utc_now)

    class Config:
        populate_by_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str}

class ChatSession(BaseModel):
    """
    Represents a user chat session.
    
    Attributes:
        id (str): Unique identifier for the chat session.
        user_id (str): Identifier for the user who owns the chat session.
        title (str): Title of the chat session.
        title_generated (bool): Whether the title has been auto-generated by LLM.
        created_at (datetime): Timestamp when the chat session was created.
        updated_at (datetime): Timestamp when the chat session was last updated.
    """
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    user_id: str = Field(..., index=True)
    title: str = Field(default="New Chat", max_length=100)
    title_generated: bool = Field(default=False)
    created_at: datetime = Field(default_factory=get_utc_now)
    updated_at: datetime = Field(default_factory=get_utc_now)

    class Config:
        populate_by_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str}