"use client";

import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { Pencil, Trash2 } from "lucide-react";
import { formatTime as formatMs } from "@/lib/stats-utils";
import { TIMER_EVENTS } from "@/lib/timer-events";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Field, Input, Textarea } from "@/components/ui/Field";
import { IconButton } from "@/components/ui/IconButton";
import { Modal } from "@/components/ui/Modal";
import { SegmentedControl } from "@/components/ui/SegmentedControl";
import { ShareMenu } from "@/components/ui/ShareMenu";
import { Skeleton } from "@/components/ui/Skeleton";
import { TimeValue } from "@/components/ui/TimeValue";

const ScramblePreview = dynamic(() => import("./ScramblePreview"), {
  loading: () => <Skeleton radius="panel" className="w-full h-48" />,
  ssr: false,
});

const SolveEditModal = dynamic(() => import("./SolveEditModal"), { ssr: false });

type Penalty = "none" | "+2" | "DNF";

export interface TimerRecord {
  id: string;
  time: number;
  timestamp: Date;
  scramble: string;
  penalty: Penalty;
  finalTime: number;
  event: string;
  notes?: string;
  tags?: string[];
  timerMode?: "normal" | "manual" | "stackmat";
}

export function getEventName(eventId: string) {
  return TIMER_EVENTS.find((event) => event.id === eventId)?.name ?? eventId;
}

export function formatSolveTime(timeMs: number, penalty: Penalty = "none") {
  if (penalty === "DNF" || timeMs === Infinity || timeMs === 0) return "DNF";
  return formatMs(timeMs);
}

export function TimerModeBadge({ mode }: { mode?: TimerRecord["timerMode"] }) {
  if (!mode || mode === "normal") return null;
  return (
    <Badge tone={mode === "manual" ? "info" : "accent"}>
      {mode === "manual" ? "Manual" : "Stackmat"}
    </Badge>
  );
}

const parseTags = (value: string) =>
  value
    .split(",")
    .map((tag) => tag.trim())
    .filter(Boolean);

interface SolveDetailsModalProps {
  solve: TimerRecord | null;
  isOpen: boolean;
  onClose: () => void;
  onApplyPenalty: (solveId: string, penalty: Penalty) => void;
  onDeleteSolve: (solveId: string) => void;
  onUpdateSolve?: (solveId: string, notes?: string, tags?: string[]) => void;
  onEditTime?: (solveId: string, time: number, penalty: Penalty) => void;
}

export default function SolveDetailsModal({
  solve,
  isOpen,
  onClose,
  onApplyPenalty,
  onDeleteSolve,
  onUpdateSolve,
  onEditTime,
}: SolveDetailsModalProps) {
  const [editingNotes, setEditingNotes] = useState(false);
  const [editingTags, setEditingTags] = useState(false);
  const [notesValue, setNotesValue] = useState("");
  const [tagsValue, setTagsValue] = useState("");
  const [showEditModal, setShowEditModal] = useState(false);

  useEffect(() => {
    if (solve) {
      setNotesValue(solve.notes || "");
      setTagsValue(solve.tags?.join(", ") || "");
    }
  }, [solve]);

  useEffect(() => {
    if (!isOpen) {
      setEditingNotes(false);
      setEditingTags(false);
    }
  }, [isOpen]);

  if (!solve) return null;

  const shareText = () => {
    const penalty = solve.penalty === "none" ? "" : ` (${solve.penalty})`;
    const dateTime = solve.timestamp.toLocaleString("en-US", {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
    return `Generated by CubeDev\n${formatSolveTime(solve.finalTime, solve.penalty)}${penalty}\n${solve.scramble}\n${dateTime}`;
  };

  const save = () =>
    onUpdateSolve?.(solve.id, notesValue, parseTags(tagsValue));

  const cancelNotes = () => {
    setNotesValue(solve.notes || "");
    setEditingNotes(false);
  };

  const cancelTags = () => {
    setTagsValue(solve.tags?.join(", ") || "");
    setEditingTags(false);
  };

  return (
    <>
      <Modal open={isOpen} onClose={onClose} size="md" mobile="fullscreen">
        <Modal.Header title="Solve Details" />
        <Modal.Body className="space-y-5">
          <div className="text-center">
            <div className="flex items-center justify-center gap-1">
              <TimeValue penalty={solve.penalty} className="text-4xl font-bold">
                {formatSolveTime(solve.finalTime, solve.penalty)}
                {solve.penalty === "+2" && "+"}
              </TimeValue>
              {onEditTime && (
                <IconButton
                  aria-label="Edit solve time"
                  icon={<Pencil />}
                  size="sm"
                  onClick={() => setShowEditModal(true)}
                />
              )}
              <ShareMenu
                title="Share solve"
                data={() => ({
                  title: `CubeDev Solve - ${getEventName(solve.event)}`,
                  text: shareText(),
                })}
              />
            </div>
            <p className="type-caption mt-2 flex flex-wrap items-center justify-center gap-x-2 gap-y-1">
              <span>{getEventName(solve.event)}</span>
              <span aria-hidden>·</span>
              <span>{solve.timestamp.toLocaleString()}</span>
              <TimerModeBadge mode={solve.timerMode} />
            </p>
          </div>

          <section className="rounded-(--radius-panel) border border-(--border) bg-(--surface-elevated) p-3">
            <h3 className="type-overline mb-2">Time Breakdown</h3>
            <dl className="space-y-1 text-sm font-inter">
              <div className="flex justify-between">
                <dt className="text-(--text-secondary)">Raw time</dt>
                <dd>
                  <TimeValue>{formatSolveTime(solve.time)}</TimeValue>
                </dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-(--text-secondary)">Penalty</dt>
                <dd>
                  <TimeValue penalty={solve.penalty}>
                    {solve.penalty === "none" ? "None" : solve.penalty}
                  </TimeValue>
                </dd>
              </div>
              <div className="flex justify-between border-t border-(--border) pt-1">
                <dt className="font-semibold text-(--text-primary)">Final time</dt>
                <dd>
                  <TimeValue className="font-semibold">
                    {formatSolveTime(solve.finalTime, solve.penalty)}
                  </TimeValue>
                </dd>
              </div>
            </dl>
          </section>

          <section className="space-y-2">
            <h3 className="type-overline">Scramble</h3>
            <p className="type-time text-sm text-(--text-secondary) bg-(--background-subtle) p-3 rounded-(--radius-control) border border-(--border) wrap-break-word">
              {solve.scramble}
            </p>
            <ScramblePreview scramble={solve.scramble} event={solve.event} />
          </section>

          <section className="space-y-2">
            <div className="flex items-center justify-between">
              <h3 className="type-overline">Notes</h3>
              {!editingNotes && (
                <Button variant="ghost" size="sm" onClick={() => setEditingNotes(true)}>
                  Edit
                </Button>
              )}
            </div>
            {editingNotes ? (
              <div className="space-y-2">
                <Textarea
                  value={notesValue}
                  onChange={(e) => setNotesValue(e.target.value)}
                  placeholder="Add notes about this solve…"
                  aria-label="Notes"
                  autoFocus
                  onKeyDown={(e) => {
                    if (e.key === "Escape") {
                      e.preventDefault();
                      cancelNotes();
                    }
                  }}
                />
                <div className="flex justify-end gap-2">
                  <Button variant="secondary" size="sm" onClick={cancelNotes}>
                    Cancel
                  </Button>
                  <Button
                    size="sm"
                    onClick={() => {
                      save();
                      setEditingNotes(false);
                    }}
                  >
                    Save
                  </Button>
                </div>
              </div>
            ) : (
              <p className="text-sm text-(--text-secondary) bg-(--background-subtle) p-3 rounded-(--radius-control) border border-(--border) min-h-15 font-inter">
                {solve.notes || <span className="text-(--text-muted) italic">No notes added</span>}
              </p>
            )}
          </section>

          <section className="space-y-2">
            <div className="flex items-center justify-between">
              <h3 className="type-overline">Tags</h3>
              {!editingTags && (
                <Button variant="ghost" size="sm" onClick={() => setEditingTags(true)}>
                  Edit
                </Button>
              )}
            </div>
            {editingTags ? (
              <div className="space-y-2">
                <Field hideLabel label="Tags" hint={'Separate tags with commas, e.g. "good scramble, new PB"'}>
                  <Input
                    value={tagsValue}
                    onChange={(e) => setTagsValue(e.target.value)}
                    placeholder="Add tags separated by commas…"
                    autoFocus
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        save();
                        setEditingTags(false);
                      } else if (e.key === "Escape") {
                        e.preventDefault();
                        cancelTags();
                      }
                    }}
                  />
                </Field>
                <div className="flex justify-end gap-2">
                  <Button variant="secondary" size="sm" onClick={cancelTags}>
                    Cancel
                  </Button>
                  <Button
                    size="sm"
                    onClick={() => {
                      save();
                      setEditingTags(false);
                    }}
                  >
                    Save
                  </Button>
                </div>
              </div>
            ) : (
              <div className="bg-(--background-subtle) p-3 rounded-(--radius-control) border border-(--border) min-h-10">
                {solve.tags && solve.tags.length > 0 ? (
                  <div className="flex flex-wrap gap-1.5">
                    {solve.tags.map((tag, index) => (
                      <Badge key={`${tag}-${index}`} tone="primary" shape="pill">
                        {tag}
                      </Badge>
                    ))}
                  </div>
                ) : (
                  <span className="text-(--text-muted) italic text-sm font-inter">
                    No tags added
                  </span>
                )}
              </div>
            )}
          </section>

          <section className="space-y-2">
            <h3 className="type-overline" aria-hidden>
              Penalty
            </h3>
            <SegmentedControl
              aria-label="Penalty"
              value={solve.penalty}
              onChange={(penalty) => onApplyPenalty(solve.id, penalty)}
              fullWidth
              options={[
                { value: "none", label: "OK" },
                { value: "+2", label: "+2", tone: "warning" },
                { value: "DNF", label: "DNF", tone: "error" },
              ]}
            />
          </section>
        </Modal.Body>
        <Modal.Footer
          start={
            <Button
              variant="ghost"
              className="text-(--error)! hover:bg-(--error)/10!"
              iconLeft={<Trash2 className="w-4 h-4" />}
              onClick={() => {
                onDeleteSolve(solve.id);
                onClose();
              }}
            >
              Delete solve
            </Button>
          }
        >
          <Button variant="primary" onClick={onClose}>
            Done
          </Button>
        </Modal.Footer>
      </Modal>

      {onEditTime && (
        <SolveEditModal
          isOpen={showEditModal}
          onClose={() => setShowEditModal(false)}
          currentTime={solve.time}
          currentPenalty={solve.penalty}
          onSave={(time, penalty) => {
            onEditTime(solve.id, time, penalty);
            setShowEditModal(false);
          }}
        />
      )}
    </>
  );
}
